# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_stage
  displayName: terraform stage

  jobs:
  - job: terraform_job
    displayName: terraform job
    timeoutInMinutes: 120

    steps:
    - checkout: self
    - checkout: git://AARMS/AARMS

    - script: |
    
        # Path to the backend file in the other repository
        backend_path="$(Build.SourcesDirectory)/AARMS/Services/AASI.AARMS.API"
    
        # Update the source_backend_files in terraform.tfvars
        sed -i 's|source_backend_files\s*=\s*.*|source_backend_files = "'"$backend_path"'"|' "$(Build.SourcesDirectory)/terraform-scripts/alfa-aero-core-infra/env/uat/terraform.tfvars"
    
        # Path to the backend file in the other repository; i.e:AARMS
        frontend_path="$(Build.SourcesDirectory)/AARMS/Web/AASI.AARMS.WEB/ClientApp"
        # Update the source_frontend_file in terraform.tfvars
        sed -i 's|source_frontend_files\s*=\s*.*|source_frontend_files = "'"$frontend_path"'"|' "$(Build.SourcesDirectory)/terraform-scripts/alfa-aero-core-infra/env/uat/terraform.tfvars"
      displayName: 'Update values of source_backend_files and source_frontend_files in terraform.tfvars'
    
    - script: |
        cat "$(Build.SourcesDirectory)/terraform-scripts/alfa-aero-core-infra/env/uat/terraform.tfvars"
      displayName: 'display content of terraform.tfvars'
    - task: TerraformInstaller@2
      inputs:
        terraformVersion: 'latest'
      displayName: terraform installer 
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
      continueOnError: true
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'OIDC-Connection'
        scriptType: 'inline'
        inlineScript: |
          aws --version
          cd $(Build.SourcesDirectory)/terraform-scripts/alfa-aero-core-infra/env/uat/
          terraform init
          terraform plan
          terraform apply --auto-approve
      displayName: 'terraform init and plan'